/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fureverhome_project;

/**
 *
 * @author reggie
 */

import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

public class Animal_Data_Panel extends javax.swing.JPanel {

    koneksi kon = new koneksi();
    
    /**
     * Creates new form Animal_Data_Panel
     */
    public Animal_Data_Panel() {
        initComponents();
        
        kon.setConnection();
    }
    
    public void setName(String name)
    {
        name_label.setText(name);
    }
    
    
    public void setBreed(String breed)
    {
        breed_label.setText(breed);
    }

    
    public void setPicture(ImageIcon picture)
    {
        picture_label.setIcon(picture);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picture_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        breed_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 231, 203));
        setForeground(new java.awt.Color(109, 69, 33));
        setRequestFocusEnabled(false);

        picture_label.setForeground(new java.awt.Color(109, 69, 33));
        picture_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picture_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 69, 33), 5));
        picture_label.setPreferredSize(new java.awt.Dimension(180, 240));

        name_label.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 18)); // NOI18N
        name_label.setForeground(new java.awt.Color(109, 69, 33));
        name_label.setText("name");

        breed_label.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        breed_label.setForeground(new java.awt.Color(109, 69, 33));
        breed_label.setText("breed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picture_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label)
                    .addComponent(breed_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(picture_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breed_label)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breed_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel picture_label;
    // End of variables declaration//GEN-END:variables
}
