/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fureverhome_project;

/**
 *
 * @author reggie
 */

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.util.*;

public class User_Login extends javax.swing.JFrame {

    koneksi kon = new koneksi();
    
    /**
     * Creates new form FormUser_Menu
     */
    public User_Login() {
        this.setTitle("Fur-Ever Home");
        
        initComponents();
        kon.setConnection();
        
        setIconImage();
        
        Color myBeige = new Color(255,231,203);
        getContentPane().setBackground(myBeige);
    }
    
        //change window icon
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/original_icon_file.jpeg")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        password_field = new javax.swing.JTextField();
        full_name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password_pwField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optionsMenu_signup = new javax.swing.JMenuItem();
        optionsMenu_exit = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 231, 203));
        setFont(new java.awt.Font("DM Sans", 1, 10)); // NOI18N
        setMaximumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        full_name.setFont(new java.awt.Font("DM Sans", 1, 18)); // NOI18N
        full_name.setForeground(new java.awt.Color(109, 69, 33));
        full_name.setText("Username :");

        jLabel1.setFont(new java.awt.Font("DM Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 69, 33));
        jLabel1.setText("Password :");

        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });

        submit_button.setFont(new java.awt.Font("DM Sans", 1, 14)); // NOI18N
        submit_button.setForeground(new java.awt.Color(109, 69, 33));
        submit_button.setText("Submit");
        submit_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Advent Pro SemiExpanded", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 69, 33));
        jLabel2.setText("Login");

        password_pwField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_pwFieldActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_only_resized_100x100.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(109, 69, 33));
        jMenuBar1.setForeground(new java.awt.Color(109, 69, 33));

        jMenu1.setText("Options");

        optionsMenu_signup.setText("Sign Up");
        optionsMenu_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsMenu_signupActionPerformed(evt);
            }
        });
        jMenu1.add(optionsMenu_signup);

        optionsMenu_exit.setText("Exit");
        optionsMenu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsMenu_exitActionPerformed(evt);
            }
        });
        jMenu1.add(optionsMenu_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(submit_button)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(full_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(full_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_pwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addComponent(submit_button)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        String username = username_field.getText();
        String password = password_pwField.getText();
        
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the forms.");
        }
        
        else {
            try {
                String query = "select * from tb_user where user_username='"+username+"' and user_password='"+password+"'";
                ResultSet rs = kon.st.executeQuery(query);
                
                if (rs.next()) {
                    // if username and password is true
                    if (username.equals("furever_admin"))
                    {
                        dispose();
                        Admin_AddAnimal add_animal = new Admin_AddAnimal();
                        add_animal.show();
                    }
                    
                    else 
                    {
                        dispose();
                        User_Homepage homepage = new User_Homepage();
                        homepage.show();
                    }
//                    User_Homepage userHP = new User_Homepage();
//                    userHP.show();
                }
                
                else 
                {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password. Please try again.");
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Login Error: "+ex);
                
            }
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void optionsMenu_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsMenu_signupActionPerformed
        // TODO add your handling code here:
        dispose();
        
        User_SignUp signup = new User_SignUp();
        signup.show();
    }//GEN-LAST:event_optionsMenu_signupActionPerformed

    private void optionsMenu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsMenu_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_optionsMenu_exitActionPerformed

    private void password_pwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_pwFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_pwFieldActionPerformed

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel full_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenuItem optionsMenu_exit;
    private javax.swing.JMenuItem optionsMenu_signup;
    private javax.swing.JTextField password_field;
    private javax.swing.JPasswordField password_pwField;
    private javax.swing.JButton submit_button;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
